# 全局costmap
global_costmap:
  # 全局costmap参考坐标系
  global_frame: map
  # 机器人参考坐标系
  robot_base_frame: base_footprint

  update_frequency: 1
  publish_frequency: 1

  track_unknown_space: true
  rolling_window: false
  transform_tolerance: 10
  resolution: 0.05

  # static_map: true

  # 配置图层插件
  plugins:
    # 静态层
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    # 障碍层
    - { name: obstacle_layer, type: "costmap_2d::VoxelLayer" }
    # 膨胀层
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
