# 局部costmap
local_costmap:
  # 局部costmap参考坐标系
  global_frame: map #rtabmap_odom
  # 机器人参考坐标系
  robot_base_frame: base_footprint

  update_frequency: 10
  publish_frequency: 10

  # static_map: false  #不使用静态地图
  rolling_window: true #使用滚动地图
  width: 5
  height: 5
  resolution: 0.05
  transform_tolerance: 10.0

  # 配置图层插件
  plugins:
    - { name: obstacle_layer, type: "costmap_2d::VoxelLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
