#{name:conservative_reset, type:clear_costmap_recovery/ClearCostmapRecovery},
#{name:rotate_recovery,type:rotate_recovery/RotateRecovery},
#{name:aggressive_reset,type:clear_costmap_recovery/ClearCostmapRecovery}

# 恢复模式下执行的操作
recovery_behavior_enabled: true #(bool, default:true) #是否启用move_base修复机制
controller_frequency: 5.0 #(double, default:20.0) #控制循环的执行频率，也可认为是速度发布指令的频率
planner_patience: 10.0 #(double, default:5.0) #规划器在空间清除操作前,能够进行路径规划的时间
conservative_reset_dist: 1.5 #(double, default:3.0) #当在地图中清理出空间时，距离机器人几米远的障碍会从代价地图中清除
clearing_rotation_allowed: true #(bool, default:true) #在清除空间操作时，是否允许底座原地旋转
shutdown_costmaps: false #(bool, default:false) #当move_base不活动时，是否关闭costmaps
oscillaiton_timeout: 5 #(double, default:0.0) #执行修复机制前，允许振荡的时长
oscillation_distance: 0.5 #(double, default:0.5) #来回运动在多大距离以上不会被认为是振荡
planner_frequency: 0 #(double, default:0.0) #全局规划操作的执行频率。如果设置为0.0，则全局规划器仅在接收到新的目标点或者局部规划器报告路径堵塞时才会重新执行规划操作
max_planning_retries: 100 #(int32, default:-1) #在执行修复操作前，允许规划器重新规划路径的次数，-1.0表示无限多次重新尝试

#配置movebase的路径规划插件
#base_global_planner: navfn/NavfnROS 
base_global_planner: global_planner/GlobalPlanner 
#base_global_planner: carrot_planner/CarrotPlanner 
# 局部路径插件
base_local_planner: dwa_local_planner/DWAPlannerROS  
#base_local_planner: base_local_planner/TrajectoryPlannerROS 
#base_local_planner: teb_local_planner/TebLocalPlannerROS 