obstacle_range: 4.0
raytrace_range: 4.5

footprint: [[-0.15, -0.1], [-0.15, 0.1], [0.15, 0.1], [0.15, -0.1]]
# robot_radius: 0.19

inflation_radius: 1
cost_scaling_factor: 10

map_type: costmap

# map_type: costmap
# observation_sources: scan
# scan: {sensor_frame: base_footprint, 
# data_type: LaserScan, 
# topic: scan, 
# marking: true, 
# clearing: true
# }