local_costmap:
  global_frame: odom_combined
  robot_base_frame: base_footprint

  update_frequency: 10
  publish_frequency: 10
  transform_tolerance: 0.5

  resolution: 0.01 # 解析度，即地图分辨率
  static_map: false  
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.05



